version: 1.0.0.{build}

image: Visual Studio 2017

platform: x64

branches:
  only:
    - master

clone_folder: c:\gopath\src\github.com\containous\traefik\

environment:
  GOPATH: c:\gopath
  DOCKER_USERNAME:
    secure: 4y743ZuqLrJwRFN72TNYSQ==
  DOCKER_PASSWORD:
    secure: BvKwqfmKvDxuJq77hWwb6Q==
  DOCKER_IMAGE: traefik-windows
  NODEJS_VERSION: "6"

install:
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env
  - npm install -g windows-build-tools
  - docker version

build_script:
  - ps: .\build.ps1 -Verb runAs

deploy_script:
  - docker login -u="$env:DOCKER_USERNAME" -p="$env:DOCKER_PASS"
  - docker push "${env:DOCKER_USERNAME}/${DOCKER_IMAGE}:${env:APPVEYOR_BUILD_ID}"

artifacts:
  - path: out\traefik
    name: binary